✨ Add page break after h2
Keldos-Li/typora-latex-theme pull request #132
Opened 2024-02-29 04:27 UTC by Zxis233

Give an option to choose whether to enable page break after each h2 title except the first one.

2024-02-29 16:47 UTC, Keldos-Li commented
🤔should correct: **_after_** h2 => **_before_** h2

2024-03-01 03:16 UTC, Zxis233 commented
> 🤔should correct: **_after_** h2 => **_before_** h2

yeah, it's a typo :P

2024-03-01 14:57 UTC, Keldos-Li commented
emm，请再push一个commit更改代码中的写法

2024-03-02 02:10 UTC, Zxis233 commented
> emm，请再push一个commit更改代码中的写法

其实功能是“使每个二级标题单独一页显示”，所以强制分页在二级标题下的内容之后(?)
不过保持一致性我都改成一样吧，免得歧义

2024-03-03 08:00 UTC, Keldos-Li approved these changes

2024-03-14 12:19 UTC, Keldos-Li commented
@RalXYZ

2024-04-15 17:26 UTC, RalXYZ requested changes
@Zxis233 @Keldos-Li  抱歉拖了这么久才审核，这个 pr 的审核请求邮件被我不小心忽略掉了。  
我对这个 pr 的意见主要有两个点。  

1. `page-break-before` 这个属性目前已经 deprecated 了，应该换成 `break-before`。
2. 我不太认同把默认值设为 `avoid`。我觉得默认的行为没必要改，维持原始值是最稳妥的。我换种说法，需要分页的地方用 `always` 这个肯定没问题，不需要分页的地方我觉得应该维持原样用 `auto`。

更细节的观点我已经在相关位置进行了批注。我不知道大家对此有无其他看法。如果认同这个观点，辛苦 @Zxis233 修改并测试一下，再提交一个 commit。

2024-04-15 17:26 UTC, RalXYZ commented on src/scss/settings.scss
> +  --page-break-before-h2: void;
请再确认一下，这里确定是 `void` 吗？我在 [`page-break-before` 的 MDN 文档](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before) 里并没有找到 `void` 这个值。  
此外，根据我的理解，开关的默认值不应该是显式的开或者关，而应该是字面意思的“默认值”，从而保持尽可能大的兼容性。如，针对 `page-break-before` 这个属性而言，它的默认值是 `auto`。

2024-04-15 17:26 UTC, RalXYZ commented on src/scss/text.scss
> +    page-break-before: var(--page-break-before-h2);
`page-break-before` 这个 tag 已被弃用，参见[它的MDN文档](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before)。根据文档指引，请考虑使用 [`break-before`](https://developer.mozilla.org/en-US/docs/Web/CSS/break-before)。

2024-04-15 17:26 UTC, RalXYZ commented on src/scss/text.scss
> +    page-break-before: avoid;
我认为无需显式地更改 `page-break-before` 这个属性在 `first-of-type` 情况下的值为 `avoid`。请考虑保持它的值为 `auto`，即维持默认情况。

2024-04-15 17:28 UTC, RalXYZ commented
再次为我的粗心和拖延表示歉意，以后我尽可能避免拖这么久。感谢 @Zxis233 的贡献和 @Keldos-Li 的工作。

2024-04-16 00:20 UTC, Zxis233 commented
> @Zxis233 @Keldos-Li 抱歉拖了这么久才审核，这个 pr 的审核请求邮件被我不小心忽略掉了。 我对这个 pr 的意见主要有两个点。
> 
> 1. `page-break-before` 这个属性目前已经 deprecated 了，应该换成 `break-before`。
> 2. 我不太认同把默认值设为 `avoid`。我觉得默认的行为没必要改，维持原始值是最稳妥的。我换种说法，需要分页的地方用 `always` 这个肯定没问题，不需要分页的地方我觉得应该维持原样用 `auto`。
> 
> 更细节的观点我已经在相关位置进行了批注。我不知道大家对此有无其他看法。如果认同这个观点，辛苦 @Zxis233 修改并测试一下，再提交一个 commit。

收到。感谢指正。
另外，不知道typora是否支持在markdown元数据的地方传入参数？类似´typora-copy-images-to´可以强制指定图片保存方式，这样就不需要来回修改css文件了 XP

2024-04-16 02:59 UTC, RalXYZ commented
> 另外，不知道typora是否支持在markdown元数据的地方传入参数？
这个我之前没了解过，我理解是没有这种功能，你可以调查一下

2024-04-17 09:53 UTC, closed without merging