chore: make compatible with dart-sass
Keldos-Li/typora-latex-theme pull request #160
Opened 2024-10-31 14:48 UTC by Bubbu0129

Fix #158.

2024-11-01 09:17 UTC, RalXYZ requested changes
请将 dart-sass 版本指定为 1.79.6

2024-11-01 09:17 UTC, RalXYZ commented on .github/workflows/dev-build.yml
> +          fileName: 'dart-sass-*-linux-x64.tar.gz'
在这里，我们要控制 sass 的版本号，不能这样简单地通配了。这是因为，sass 的版本迭代速度快；而我们要确保我们的项目能一直被符合预期地构建，不受 sass 版本的影响。
建议把这里改为`1.79.6` ，我不确定能不能直接字面替换掉你这个通配符，这个可能还需再确认一下。

2024-11-01 09:17 UTC, RalXYZ commented on .github/workflows/release.yml
> +          fileName: 'dart-sass-*-linux-x64.tar.gz'
这里也许要做对应的修改

2024-11-01 09:22 UTC, RalXYZ commented
![image](https://github.com/user-attachments/assets/790c6103-9f81-4e54-b315-893d1ec2f6ee)

另外，提醒您关注一下 committer/author 信息；当前的情形可能不符合您的预期
如果您有意为之，则忽略这个提醒

2024-11-01 15:36 UTC, RalXYZ approved these changes
LGTM

2024-11-01 15:40 UTC, RalXYZ commented
> ![image](https://private-user-images.githubusercontent.com/19510622/382240679-790c6103-9f81-4e54-b315-893d1ec2f6ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzU4NzQsIm5iZiI6MTczMDQ3NTU3NCwicGF0aCI6Ii8xOTUxMDYyMi8zODIyNDA2NzktNzkwYzYxMDMtOWY4MS00ZTU0LWIzMTUtODkzZDFlYzJmNmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE1MzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZDFmOWMzNWJkODJjYTk3YTk1NWJkMzIyMzc3Zjc3ZjllMjVhY2QzMWQwMGVmNjQyNDNiM2E2OTNiN2NiNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YpVSd6WE2oK2HlDo4lLG6tBUwVIbKefLdlAmWlfa58w)
> 
> 另外，提醒您关注一下 committer/author 信息；当前的情形可能不符合您的预期 如果您有意为之，则忽略这个提醒

@Bubbu0129 最后再确认下，您确定您这个 pr 里的 committer/author 信息没问题么？没问题我就合入主线了

2024-11-01 16:20 UTC, Bubbu0129 commented
谢谢提醒！已修改。
Issue 中提到的问题请注意 [#158](https://github.com/Keldos-Li/typora-latex-theme/issues/158#issuecomment-2451775394)

2024-11-02 04:42 UTC, Keldos-Li approved these changes

2024-11-02 05:41 UTC, merged