feat: Modify and footnote superscript styles to match LaTeX theme
Keldos-Li/typora-latex-theme pull request #172
Opened 2024-12-17 09:18 UTC by Linho1219

Remove footnote superscript background and padding; adjust brackets and spacing of footnote labels

**Note:** In the contribution guidelines, PRs should be submitted to the `develop` branch. However, there's no branch named `develop` here now, so I submitted it to the main branch. The possible reason may be that the `develop` branch has been deleted, and the documentation has not been updated. If you believe submitting directly to the main branch is inappropriate, please let me know which branch I should submit to and close this PR.

2024-12-17 11:52 UTC, RalXYZ commented
> **Note:** In the contribution guidelines, PRs should be submitted to the `develop` branch. However, there's no branch named `develop` here now, so I submitted it to the main branch. The possible reason may be that the `develop` branch has been deleted, and the documentation has not been updated. If you believe submitting directly to the main branch is inappropriate, please let me know which branch I should submit to and close this PR.

@Linho1219 Thank you for respecting our contribution guidelines. After reviewing them, I found that some information was outdated, and I have made the necessary updates. You do not need to submit a PR to the develop branch.

From my side, there are no issues with the process. Regarding the functionality of this PR (whether it meets the expectations), please @Keldos-Li review it.

2024-12-17 12:11 UTC, Keldos-Li commented
Thank you! I see that since we have started working on the footnote section, we might as well complete the work in this PR. I looked at the remaining tasks, which might include:
- [ ] Add [] before and after sup label as well
- [ ] Adjust the paragraph style of the endnote block to avoid excessive line spacing
- [ ] footnote may exceed one line and need indentation adjustment

I expect to start trying to improve these features tomorrow and prepare to commit directly to your branch. If you have time, you can also work on improving the submission first! Once these tasks are completed, we will merge it into main~ Thanks again~

2024-12-19 08:23 UTC, Keldos-Li approved these changes
Also @Linho1219. 
我还是用中文了，各位可以看看现在的效果，如果之后检查没什么问题就以这个合并啦？

2024-12-22 14:48 UTC, Keldos-Li requested changes
导出表现错误。等我再修……

2024-12-22 17:38 UTC, Linho1219 commented
应当是 Typora 的部分内置样式采用了 `@media print`。过两天找一找

2024-12-27 12:45 UTC, Keldos-Li approved these changes
改好了，各位重新review一下

2025-01-06 16:43 UTC, Keldos-Li approved these changes

2025-01-07 04:45 UTC, merged