Migrate some docs from README to wiki
Keldos-Li/typora-latex-theme pull request #43
Opened 2021-11-22 07:44 UTC by RalXYZ

For simplicity concern, some docs are migrated to wiki.

2021-11-22 09:04 UTC, Keldos-Li commented
https://github.com/Keldos-Li/typora-latex-theme/commit/ae58ac6393082927f2cbc96947c0a1f7ed8c3c53#r60668477

2021-11-22 17:33 UTC, Keldos-Li requested changes
见前面的评论

2021-11-23 00:35 UTC, RalXYZ commented
> 感觉这段可以保留？这是想留给外国朋友看的，避免人家从typora- themes点进来为一个那么多star的主题竟不是英文readme感到惊讶和不爽（？）

我觉得还好？  
在我看来，外国朋友看到这个项目，如果不愿意花费更多时间的话，可能就直接关闭页面了。如果他真的有需求，那么大概会用浏览器的在线翻译软件进行一个翻译，这样，他也能获得合适的引导。以及，未来*说不定*我们会增加一定的其他语言/文字的文档。  
简而言之，我觉得他们能懂。

2021-11-23 00:53 UTC, RalXYZ reviewed
修改了安装教程的相关细节

2021-11-23 00:56 UTC, Keldos-Li approved these changes

2021-11-23 01:13 UTC, merged