add Joplin support
Keldos-Li/typora-latex-theme pull request #56
Opened 2021-11-28 14:56 UTC by stephanoskomnenos

试着把 typora-latex 主题移植到 Joplin 上，当前还存在一些问题，但大致的效果还不错。（只在 Win 上测试过）

./Suppemental 里有两者根据同一 Markdown 生成的 PDF，可以对比看一下效果。

问题有以下几点。一个是 Joplin 的问题：

- Joplin 不能识别段首空格（虽然可以在主题文件里给所有段落开头加上空格）
- Joplin 不支持 YAML front matter，会直接显示在输出的 PDF 里
- Joplin 的所见即所得模式有一些 bug，比如 https://github.com/laurent22/joplin/issues/5800 
- Joplin 不支持多个主题同时导入，想要换主题只能去手动替换掉主题文件
- 一些语法支持（比如 `:emoji:` ，`[^1^]` ，`H~2~O` 等）需要在 Joplin 的设置里开启
- Joplin 没有主题定制指南

还有一个是这个主题的问题：

- 所有表格的第一行背景颜色都是灰色
- 一些缩进比 typora-latex 更小
- `[TOC]` 生成目录的样式，code block 的样式，暂时不知道怎么改
- 暂时没有在非 Win 系统上测试过

2021-12-01 02:16 UTC, RalXYZ commented
请您在您 fork 的 GitHub 仓库的 develop 分支进行 fetch upstream:  
![image](https://user-images.githubusercontent.com/19510622/144159555-51c52b93-53c2-4ef1-a345-e248b0716aeb.png)

2021-12-01 02:19 UTC, RalXYZ commented
不好意思，先等一下，暂时不要 fetch upstream。我这边还有一点问题没有处理完。

2021-12-01 02:24 UTC, RalXYZ commented
> 不好意思，先等一下，暂时不要 fetch upstream。我这边还有一点问题没有处理完。

问题已解决，您现在可以 fetch upstream 了。

2021-12-01 16:05 UTC, stephanoskomnenos commented
ok. 已经 fetch 了。

2021-12-02 02:09 UTC, RalXYZ commented
我做了初步的检查。  
您贡献的 Joplin 主题在 Linux Joplin 中，能使得样例文档得到几乎完全符合预期的显示。Wonderful job, thank you very much👍

接下来，我将会：
1. 审核您贡献的源代码
2. 列出一个功能清单，记录它和目前 Typora 主题的功能差异

---

下面是目前 Linux Joplin 在使用本主题后的效果截图  

![image](https://user-images.githubusercontent.com/19510622/144343254-5308bf3e-ba2b-4654-801c-3aac6a5f9392.png)  

![image](https://user-images.githubusercontent.com/19510622/144343342-46d5cf0e-444e-4c11-8ee1-b15a97f1250c.png)  

![image](https://user-images.githubusercontent.com/19510622/144343411-a3fea1a4-ee0b-442a-8ad7-4b2ef3811d3c.png)

2021-12-05 14:26 UTC, RalXYZ requested changes
我完成了审核。大部分地方都没有问题，唯独：  
- 我们希望您保留 `Supplemental` 目录的原始内容，不对其做任何修改

因此，在这个拉取请求被合并前，您需要移除您对 `Supplemental` 目录的所有修改。以下选择可以被接受：  
- 再进行一个提交，内容是 `revert` 您对 `Supplemental` 目录的所有修改

我们不建议您使用 `git filter-branch` 等篡改 git 树的操作。

2021-12-06 11:26 UTC, stephanoskomnenos commented
`Supplemental` 目录已经恢复了

2021-12-07 11:41 UTC, RalXYZ approved these changes

2021-12-07 16:47 UTC, Keldos-Li reviewed
我在想，latex-theme.scss的部分能不能只开一个`if $tool == "joplin" {}`，然后把现在分散在各个地方的joplin单独设置放在这里面？现在感觉整个代码很乱……

（不过从可维护性角度来说，可能现在的状态更合适？）

2021-12-08 00:09 UTC, RalXYZ commented
> 我在想，latex-theme.scss的部分能不能只开一个`if $tool == "joplin" {}`，然后把现在分散在各个地方的joplin单独设置放在这里面？现在感觉整个代码很乱……
> 
> （不过从可维护性角度来说，可能现在的状态更合适？）

我觉得可能也没有更好的解决方案了？确实是可维护性的问题。

2021-12-08 10:10 UTC, Keldos-Li approved these changes
暂时先这样吧

2021-12-08 11:31 UTC, merged

2021-12-11 14:53 UTC, RalXYZ commented
我来同步一下当前进展。
这个 pr 的后续是 #59 ；正如其中所言，我们会在添加足量的文档后，再考虑将其合并进主分支。  

当然，这个周期可能会比较漫长——可能会需要一个月或更长的时间。这是因为，当前主题仍然存在一些显著的问题亟待解决；相比于增添新功能，我们会优先处理已有功能的问题，更何况，增添 Joplin 支持的任务量较大。
这个 pr 做出的贡献一定会在未来的某个时间节点被合并到主分支里，但目前还不清楚具体是什么时候，至少目前规划的 [`v0.2.7`](https://github.com/Keldos-Li/typora-latex-theme/milestone/1) 中不会合并与 Joplin 相关的任何内容。  

如果您对本项目的排期感兴趣，建议您关注我们的 [milestone](https://github.com/Keldos-Li/typora-latex-theme/milestones)。如果您能帮我们撰写 Joplin 相关的文档，也欢迎您和我们继续联系。